export default {
  TEXT: 'text',
  AUTOCOMPLETE: 'autocomplete',
  CHECKBOX: 'checkbox',
  COLORPICKER: 'colorpicker',
  DATEFILTER: 'datefilter',
  DATEPICKER: 'datepicker',
  NUMBER: 'number',
  FILE: 'file',
  GRIDFORM: 'gridform',
  HIDDEN: 'hidden',
  PASSWORD: 'password',
  SELECT: 'select',
  SWITCH: 'switch',
  TEXTAREA: 'textarea',
  CHECKBOX_GROUP: 'checkbox_group',
  RADIO_GROUP: 'radio_group',
  MASKED: 'masked',
};
